<html>
<head>
	

	<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
	
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
	
	
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
	<style>
		.navbar{
			background-color:#003300;
			
		}
		.container{
			width: 500px;
			margin:auto;
			text-align:center;
		}
		
	</style>

</head>
<body>

<nav class="navbar">
	<div class="container">
	  <div class="row" >
		
		<div class="col-lg-12">
		  <img class="banner" src="https://www.feutech.edu.ph/assets/img/banner.png">
		</div>

	  </div>
	</div>
  
</nav>
</body>
</html>