<html>
<head>
	

	<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
	
	<style>
		.navbar{
			background-color:#003300;
			
		}
		.container{
			width: 500px;
			margin:auto;
			text-align:center;
		}
		
	</style>

</head>
<body>

<nav class="navbar">
	<div class="container">
	  <div class="row" >
		
		<div class="col-lg-12">
		  <img class="banner" src="https://www.feutech.edu.ph/assets/img/banner.png">
		</div>

	  </div>
	</div>
  
</nav>
</body>
</html>