<html>

<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

	
	  <div >
		<ul class="nav nav-tabs card-header-tabs">
		  <li class="nav-item">
			<a class="nav-link" href="userpaneltest-createticket.php">Create Ticket</a>
		  </li>
		  <li class="nav-item">
			<a class="nav-link" href="userpaneltest-pending.php">Pending Tickets</a>
		  </li>
		  <li class="nav-item">
			<a class="nav-link" href="#">Completed Tickets</a>
		  </li>
		 
		  
		</ul>
	  </div>
	  
	

  </div>
  
  <div class="container-fluid">    
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
      <ul class="navbar-nav nav ">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle  href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Notifications<span class="badge bg-secondary">9</span></a>
			<ul class="dropdown-menu">
				<li><a class="dropdown-item" href="#">Action</a></li>
				<li><a class="dropdown-item" href="#">Another action</a></li>
				<li><a class="dropdown-item" href="#">Something else here</a></li>
				<li><hr class="dropdown-divider"></li>
				<li><a class="dropdown-item" href="#">Separated link</a></li>
			</ul>
		</li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Username
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="#">Information</a></li>
            <li><a class="dropdown-item" href="#">Sign Out</a></li>
            
          </ul>
        </li>
      </ul>
    </div>
  </div>

</nav>
	
	
 
</body>
</html>